name: CD - Deploy API Node.js para VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Copiar arquivos via SCP para VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home/${{ secrets.SERVER_USER }}/deploy-controle-estoque-zoonoses-api"

      - name: SSH e Deploy via Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/deploy-controle-estoque-zoonoses-api
            docker stop zoonoses-api || true
            docker rm zoonoses-api || true
            docker build -t zoonoses-api .
            docker run -d --name zoonoses-api -p 3000:3000 --env-file .env zoonoses-api