# Nome do seu workflow.
name: CI - Pipeline Completo da API

# Gatilhos: Roda em pushes e pull requests para as branches principais.
on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

# Define os jobs que serão executados.
jobs:
  # -----------------------------------------------------------------
  # Job 1: Roda apenas os testes unitários. É rápido e não precisa de banco.
  # -----------------------------------------------------------------
  unit-tests:
    name: Testes Unitários
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache das dependências npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes unitários
        run: npx jest --testPathPattern=__tests__/unit/ --verbose

  # -----------------------------------------------------------------
  # Job 2: Roda os testes de integração, que precisam de um banco de dados.
  # -----------------------------------------------------------------
  integration-tests:
    name: Testes de Integração
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password_para_teste
          POSTGRES_DB: zoonoses_test_db
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache das dependências npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes de integração
        env:
          NODE_ENV: test
          CI: true
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_NAME: zoonoses_test_db
          DB_PASS: postgres
          APP_SECRET: segredo_para_testes_no_ci
        run: npx jest --testPathPattern=__tests__/integration/ --runInBand --verbose

  # -----------------------------------------------------------------
  # Job 3: Tenta construir a imagem Docker se todos os testes passarem.
  # -----------------------------------------------------------------
  docker-build:
    name: Build da Imagem Docker
    runs-on: ubuntu-latest
    # Este job só roda se AMBOS os jobs de teste passarem.
    needs: [unit-tests, integration-tests]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build da imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false # Importante: Apenas constrói, não envia para nenhum registro.
          tags: zoonoses-api:test-build